# Generated by Django 2.1 on 2018-08-20 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import stock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_list', djongo.models.fields.ArrayModelField(model_container=stock.models.Record)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
