# Generated by Django 2.1 on 2018-09-21 10:20

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='category_groups',
            field=djongo.models.fields.ListField(default=[]),
        ),
    ]
